/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/BNlwiZ6lNcO
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Cabin } from 'next/font/google'
import { Manrope } from 'next/font/google'

cabin({
  subsets: ['latin'],
  display: 'swap',
})

manrope({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/

const elements = [
  <iframe key="1" className="w-full aspect-video" src="https://www.youtube.com/embed/ye2bnlj4E1E?si=1Q17qLEdBuS0FxI8" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>,
  <iframe key="2" className="w-full aspect-video" src="https://www.youtube.com/embed/EA1ARzZkACc?si=bu0J-jVe82H8tG7L" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
]

export function Main() {
  return (
    <>
      <header className="bg-gradient-to-r from-[#2c5282] to-[#4c51bf] py-6 px-4 md:px-8">
        <h1 className="text-3xl font-bold text-white text-center">{`Kerem'in Fortnite Maceraları`}</h1>
      </header>
      <main className="container mx-auto my-12 grid grid-cols-1 gap-8 sm:grid-cols-2">
        {elements.map((element, idx) => (
          <div key={idx} className="rounded-lg overflow-hidden shadow-lg">
            <div className="p-4">
              {element}
            </div>
          </div>
        ))}
      </main>
    </>
  )
}
